name = "delta-sync"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "TOPIC_DO"
class_name = "TopicDO"

[[migrations]]
tag = "v1"
new_classes = ["TopicDO"]
