[target.aarch64-linux-android]
linker = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[target.x86_64-linux-android]
linker = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang"

[env]
CC_aarch64-linux-android = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"
AR_aarch64-linux-android = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CC_x86_64-linux-android = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang"
AR_x86_64-linux-android = "/Users/jdbohrman/Library/Android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
